// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit/runs/{id}": {
            "get": {
                "description": "根据审计运行 id 返回运行快照，供调试页展示运行级元数据。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "获取审计运行",
                "parameters": [
                    {
                        "type": "string",
                        "description": "审计运行 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuditRunSwaggerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/audit/runs/{id}/events": {
            "get": {
                "description": "根据审计运行 id 返回按 seq 升序排列的审计事件列表。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "获取审计运行事件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "审计运行 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuditEventsSwaggerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/audit/runs/{id}/replay": {
            "get": {
                "description": "根据审计运行 id 返回已组装的回放包，包含时间线与调试所需工件摘要。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "获取审计运行回放包",
                "parameters": [
                    {
                        "type": "string",
                        "description": "审计运行 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuditReplaySwaggerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "校验用户名密码并写入 session cookie，成功后返回当前用户信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthLoginSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthUserSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "删除当前 session 并清理浏览器中的 session cookie。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthLogoutSwaggerResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "校验 session cookie 后返回当前登录用户的基础信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取当前用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthUserSwaggerResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "使用用户名和密码创建账号，注册成功后返回用户基础信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "注册账号",
                "parameters": [
                    {
                        "description": "注册请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthRegisterSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.AuthUserSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/conversations": {
            "get": {
                "description": "返回按最近活跃时间倒序排列的 conversation 列表，包含标题、最后一条消息摘要和消息数等轻量展示字段。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "获取会话列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ConversationListSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}": {
            "get": {
                "description": "根据 conversation id 返回会话元数据，包括 provider、model、标题、最近消息摘要与消息数。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "获取会话详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ConversationDetailSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据 conversation id 删除会话及其历史消息，供 UI 删除会话项。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "删除会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ConversationDeleteSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/messages": {
            "get": {
                "description": "根据 conversation id 返回按写入顺序排列的历史消息列表，供 UI 恢复聊天内容。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "获取会话消息历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ConversationMessagesSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/hello/say": {
            "get": {
                "description": "返回一个简单的问候语，用于确认 HTTP 服务已经启动。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "示例问候接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExampleSayHelloSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/models": {
            "get": {
                "description": "返回当前服务启动时注入的全部 LLM provider/model 配置，以及前端可直接使用的默认 provider/model。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "获取模型目录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ModelCatalogSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/swagger": {
            "get": {
                "description": "将 ` + "`" + `/swagger` + "`" + ` 与 ` + "`" + `/swagger/` + "`" + ` 重定向到可直接访问的 Swagger UI 页面。",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "swagger"
                ],
                "summary": "Swagger UI 重定向",
                "responses": {
                    "302": {
                        "description": "redirect to /swagger/index.html",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/swagger/index.html": {
            "get": {
                "description": "返回内嵌的 Swagger UI HTML 页面，便于在浏览器中查看和调试 API。",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "swagger"
                ],
                "summary": "获取 Swagger UI 页面",
                "responses": {
                    "200": {
                        "description": "Swagger UI HTML",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/swagger/swagger.json": {
            "get": {
                "description": "返回当前服务使用的 Swagger JSON 文档。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "swagger"
                ],
                "summary": "获取 Swagger JSON 文档",
                "responses": {
                    "200": {
                        "description": "swagger json",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/swagger/swagger.yaml": {
            "get": {
                "description": "返回当前服务使用的 Swagger YAML 文档。",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "swagger"
                ],
                "summary": "获取 Swagger YAML 文档",
                "responses": {
                    "200": {
                        "description": "swagger yaml",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "post": {
                "description": "创建一个新的后台任务，并立即返回任务快照。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "创建任务",
                "parameters": [
                    {
                        "description": "创建任务请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TaskSwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/tasks/running": {
            "get": {
                "description": "根据 conversation id 返回最近一个非终态任务；若不存在则返回 null。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "查询会话运行中任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "conversation_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TaskSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "description": "根据任务 id 返回当前任务快照。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "获取任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TaskSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/cancel": {
            "post": {
                "description": "发起任务取消请求；若任务尚未执行，会直接进入 cancelled。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "取消任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TaskSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/events": {
            "get": {
                "description": "先补发 after_seq 之后的历史事件，再持续推送实时事件。",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "订阅任务事件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "仅返回该序号之后的事件",
                        "name": "after_seq",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE event stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "task not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/retry": {
            "post": {
                "description": "基于一个已存在任务创建新的重试任务，并返回新的任务快照。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "重试任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TaskSwaggerResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorSwaggerResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AuditEventSwaggerDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "parent_seq": {
                    "type": "integer"
                },
                "payload": {},
                "phase": {
                    "type": "string"
                },
                "ref_artifact_id": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "step_index": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "handlers.AuditEventsSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.AuditEventSwaggerDoc"
                    }
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.AuditReplayArtifactSummarySwaggerDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "encoding": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "redaction_state": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "handlers.AuditReplayArtifactSwaggerDoc": {
            "type": "object",
            "properties": {
                "body": {},
                "created_at": {
                    "type": "string"
                },
                "encoding": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "redaction_state": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "handlers.AuditReplayBundleSwaggerDoc": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.AuditReplayArtifactSwaggerDoc"
                    }
                },
                "run": {
                    "$ref": "#/definitions/handlers.AuditRunSwaggerDoc"
                },
                "timeline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.AuditReplayEventSwaggerDoc"
                    }
                }
            }
        },
        "handlers.AuditReplayEventSwaggerDoc": {
            "type": "object",
            "properties": {
                "artifact": {
                    "$ref": "#/definitions/handlers.AuditReplayArtifactSummarySwaggerDoc"
                },
                "created_at": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "parent_seq": {
                    "type": "integer"
                },
                "payload": {},
                "phase": {
                    "type": "string"
                },
                "seq": {
                    "type": "integer"
                },
                "step_index": {
                    "type": "integer"
                }
            }
        },
        "handlers.AuditReplaySwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.AuditReplayBundleSwaggerDoc"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.AuditRunSwaggerDoc": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "model_id": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "replayable": {
                    "type": "boolean"
                },
                "runner_id": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "queued",
                        "running",
                        "cancel_requested",
                        "cancelled",
                        "succeeded",
                        "failed"
                    ],
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handlers.AuditRunSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.AuditRunSwaggerDoc"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.AuthLoginSwaggerRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.AuthLogoutSwaggerData": {
            "type": "object",
            "properties": {
                "logged_out": {
                    "type": "boolean"
                }
            }
        },
        "handlers.AuthLogoutSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.AuthLogoutSwaggerData"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.AuthRegisterSwaggerRequest": {
            "type": "object",
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.AuthUserSwaggerDoc": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.AuthUserSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.AuthUserSwaggerDoc"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ConversationDeleteSwaggerData": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                }
            }
        },
        "handlers.ConversationDeleteSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.ConversationDeleteSwaggerData"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ConversationDetailSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.ConversationSwaggerDoc"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ConversationListSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ConversationSwaggerDoc"
                    }
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ConversationMessageDoc": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "model_id": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "reasoning": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tool_call_id": {
                    "type": "string"
                }
            }
        },
        "handlers.ConversationMessagesSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ConversationMessageDoc"
                    }
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ConversationSwaggerDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_message": {
                    "type": "string"
                },
                "last_message_at": {
                    "type": "string"
                },
                "message_count": {
                    "type": "integer"
                },
                "model_id": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handlers.CreateTaskRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "created_by": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "task_type": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ExampleSayHelloSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ModelCatalogSwaggerDoc": {
            "type": "object",
            "properties": {
                "default_model_id": {
                    "type": "string"
                },
                "default_provider_id": {
                    "type": "string"
                },
                "providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ModelProviderSwaggerDoc"
                    }
                }
            }
        },
        "handlers.ModelCatalogSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.ModelCatalogSwaggerDoc"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "handlers.ModelEntrySwaggerDoc": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handlers.ModelProviderSwaggerDoc": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ModelEntrySwaggerDoc"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.TaskSwaggerDoc": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "current_step_key": {
                    "type": "string"
                },
                "current_step_title": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "retry_of_task_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handlers.TaskSwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/handlers.TaskSwaggerDoc"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Agent Runtime API",
	Description:      "Agent Runtime 示例应用 API 文档。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
